orbiternassp/NASSP

Orbitersdk/samples/ProjectApollo/src_lm/LEM.h
Orbitersdk/samples/ProjectApollo/src_lm/lempanel.cpp

Panel 11 cb "AQS" should actually be "AGS"

Fix CB Spelling Error: "AQS" CB to "AGS" CB

---

Orbitersdk/samples/ProjectApollo/src_csm/CSMcomputer.cpp

I noticed the AGC didn't properly restart when a power transient occurs when the agc is in standby.
Because the program counter is set to 4000 by agc_engine upon entering standby, the hardware is never restarted.
This change removes that check, resets the standby flip-flop and turns the DSKY PSU back on.
Thanks to @thewonderidiot for clarifying along the way.

Make power transients work in standby

---

Orbitersdk/samples/ProjectApollo/src_csm/CSMcomputer.cpp
Orbitersdk/samples/ProjectApollo/src_lm/LEMcomputer.cpp

This pull request is an addition to #64 where I made some standby mode power transient changes.
The STBY and RESTART light are actually non latching and should be turned off on a power loss.

STBY and RESTART are both non latching and should turn off on transient

---

Orbitersdk/samples/ProjectApollo/src_csm/csmcautionwarning.cpp
Orbitersdk/samples/ProjectApollo/src_sys/cautionwarning.cpp
Orbitersdk/samples/ProjectApollo/src_sys/cautionwarning.h
Orbitersdk/samples/ProjectApollo/src_sys/missiontimer.cpp

@jalexb88 mentioned there were some differences between our simulation behaviour and in this [video](https://youtu.be/oxgGm8kHuig). From this video it can be clearly seen that as soon as the V35 is run the Master Alarm comes on. It also does not blink.
After discussing this in the IRC channel and examining the related schematics it was concluded that the master alarm is not supposed to blink nor that a light test causes the master alarm to be inhibited.
Our code also checks for the TestAlarms bit (ch13 bit10) in the AGC to be set to determine if a light test is in progress. @thewonderidiot pointed out that this signal is in fact completely internal to the AGC and should not be able to be read by the CWS. This functionality is being retained for now because agc_engine doesn't control the …

CWS Fixes and Tweaks

---

Orbitersdk/samples/ProjectApollo/src_csm/satswitches.cpp
Orbitersdk/samples/ProjectApollo/src_csm/satsystems.cpp
Orbitersdk/samples/ProjectApollo/src_csm/scs.cpp
Orbitersdk/samples/ProjectApollo/src_csm/scs.h
Orbitersdk/samples/ProjectApollo/src_sys/missiontimer.cpp

I've connected the EMS display to the numerics rotary and breaker similar to #71.
Also a bug has been fixed with the timers that caused them to be corrupted on a scenario load due to the buses taking some time to settle their voltages to nominal levels.

Connect EMS Numerics and timer bugfix

---

Orbitersdk/samples/ProjectApollo/src_csm/CSMcomputer.cpp
Orbitersdk/samples/ProjectApollo/src_csm/csmcautionwarning.cpp
Orbitersdk/samples/ProjectApollo/src_csm/satsystems.cpp
Orbitersdk/samples/ProjectApollo/src_csm/saturn.h
Orbitersdk/samples/ProjectApollo/src_lm/LEMcomputer.cpp
Orbitersdk/samples/ProjectApollo/src_lm/lemsystems.cpp
Orbitersdk/samples/ProjectApollo/src_lm/lm_channels.h
Orbitersdk/samples/ProjectApollo/src_sys/ioChannels.h
Orbitersdk/samples/ProjectApollo/src_sys/yaAGC/agc_engine.c
Orbitersdk/samples/ProjectApollo/src_sys/yaAGC/agc_engine.h
Orbitersdk/samples/ProjectApollo/src_sys/yaAGC/agc_engine_init.c

yaAGC now simulates the warning filter and drives the warning light (thanks @thewonderidiot :smile:).
TestAlarms has been removed. It was kept until the CMC light got driven by the AGC.
AGC Warning has also been removed from places that use it outside of the AGC itself. This signal is also internal to the AGC.
The power transient code now turns the CMC light on via channel 163, no longer sets AGC Warning and clears the RESTART light if that had been set earlier.
The LGC light now works on the LEM CWEA.

yaAGC Warning filter, Remove TestAlarms, Fix caution and warning

---

Orbitersdk/samples/ProjectApollo/src_csm/saturn.h
Orbitersdk/samples/ProjectApollo/src_csm/secs.h
Orbitersdk/samples/ProjectApollo/src_launch/LC34.cpp
Orbitersdk/samples/ProjectApollo/src_launch/LC34.h

When an abort was issued the pad would still move the arms and trigger the liftoff stream.
This prevents such things from happening.

Stop LC34 on abort

---

Orbitersdk/samples/ProjectApollo/src_csm/CSMcomputer.cpp
Orbitersdk/samples/ProjectApollo/src_lm/LEMcomputer.cpp
Orbitersdk/samples/ProjectApollo/src_lm/lemsystems.cpp
Orbitersdk/samples/ProjectApollo/src_sys/dsky.cpp

There was an issue that if the scenario was reloaded when AGC power failed the DSKY would come back on after a reload due to desync in the output channels. Setting it in the AGC next to just the output channel fixes this.
The LGC DSKY used to be wired to the general lighting breaker, This should however be wired to the same breaker as the LGC (LGC/DSKY cb). The dimmer for the display still works.

Fix DSKY desync, Wire LGC DSKY correctly

---

Orbitersdk/samples/ProjectApollo/src_sys/apolloguidance.cpp
Orbitersdk/samples/ProjectApollo/src_sys/apolloguidance.h

That code has been sitting there since 2005.
It checks if the breakers are wired at all. If not it will assume there is power.
Since we are simulating this correctly for as long as I can remember and I don't get any issues when commenting it out, I removed it.

Remove old hack in AGC power code

---

Orbitersdk/samples/ProjectApollo/src_csm/saturnmesh.cpp
Orbitersdk/samples/ProjectApollo/src_saturn/Saturn1Abort.cpp
Orbitersdk/samples/ProjectApollo/src_saturn/Saturn1Abort2.cpp

1. If CSM separates from launch vehicle with LES still attached, LES mesh no longer disapears.
2. CM docking target displays incorrectly after Apex cover jettison. (target mesh is floating outside CM) Added check to prevent CM docking target from displaying when Apex Cover is gone.
3. Adjustments to CM touchdown points.
4. S1B abort meshes SLA panels were not positioned correctly. This is now fixed.

Minor fixes:

---

Orbitersdk/samples/ProjectApollo/src_sys/imu.cpp

Since I was building in debug mode variables get initialized to a non-null value by the memory allocator. This uncovered an uninitialized variable in the IMU causing a CTD. I've added it to the constructor to explicitly null it,
I recommend everyone that works on the code to build their modules in debug mode to find issues like these.
@indy91

IMUCase was uninitialized, added to constructor.

---

Orbitersdk/samples/ProjectApollo/src_csm/saturn.cpp
Orbitersdk/samples/ProjectApollo/src_saturn/Sat5Abort1.cpp
Orbitersdk/samples/ProjectApollo/src_saturn/Saturn1Abort.cpp
Orbitersdk/samples/ProjectApollo/src_saturn/sat1bmesh.cpp

-Fixed pad aborts (vehicle no longer disappears when aborted before launch)
-Lowered aborted vehicle deletion altitude down to 30m.
-Fixed CM/SM separation while still attached to the SIVB

Saturn1B updates:

---

.gitignore

I use the XRSound addon with Orbiter2016. When I created a Project Apollo git repo in my Orbiter folder, I noticed that it doesn't ignore the XRSound files, so I added them to the .gitignore file.
I'm new to git/github, so if I've done anything wrong please let me know.

Ignore XRSound Addon

---

Orbitersdk/samples/ProjectApollo/src_sys/PanelSDK/Internals/Hsysparse.cpp

These two lines are clearly trying to calculate the cross sectional area of a spherical tank from its volume, however the equations were incorrect. This commit corrects them.
This commit also slightly improves the efficiency of H_system::Build() by allowing it to skip NULL lines in the config file.

Fixing h_Tank area calculation

---

.gitignore

I was playing around with TrackIR the other day and noticed git wanted to add my config.
This ignores it.

Add TrackIR config to gitignore

---

.gitignore

The way the gitignore was setup all source files that were not already
tracked would be ignored. If a subdirectory of a directory is ignored it
can not be negated unless all parent directories are excluded too. The
other dirs should be ignore with $dir/*

Fix and clean up .gitignore

---

Orbitersdk/samples/ProjectApollo/src_saturn/LVDC.h

- increased LVDC1B::SSTTB size, as access in LVDC1B::TimeStep (LCDC.cpp line 4785) is out_of_range.
- added comments in header to clarify usage.

Fix out of range access violation

---

Orbitersdk/samples/ProjectApollo/src_csm/satsystems.cpp
Orbitersdk/samples/ProjectApollo/src_csm/saturn.h
Orbitersdk/samples/ProjectApollo/src_csm/saturnpanel.cpp
Orbitersdk/samples/ProjectApollo/src_sys/soundlib.cpp
Orbitersdk/samples/ProjectApollo/src_sys/soundlib.h

Hi,
here's my proposal for the cabin fan sound (issue #236).
It's a small extension to the SoundLib that implements a kind of "inert volume follower".
Each time the volume is changed (via `play(...)` ) the current playing volume is getting there in a ramp-up rsp. -down manner.
Additionally to the volume ramp-up & -down I have added a frequency ramping.
This might be overkill for some sounds, but feel free to refactor this into a different class.
The impact on code using the sound is minimal:
- Change type from Sound to FadeInOutSound
- calls to play don't need the first (LOOP) parameter.
The current implementation is currently using the standard rise- and fall-times (4 seconds and 6 seconds). These values are of course arbitrary but they sound good ;)
The implementation is not using the …

#236 issue fix

---

Orbitersdk/samples/ProjectApollo/src_csm/saturn.cpp
Orbitersdk/samples/ProjectApollo/src_lm/LEM.cpp
Orbitersdk/samples/ProjectApollo/src_lm/lempanel.cpp
Orbitersdk/samples/ProjectApollo/src_lm/lemsystems.cpp
Orbitersdk/samples/ProjectApollo/src_lm/lemvc.cpp
Orbitersdk/samples/ProjectApollo/src_lm/lm_eps.cpp
Orbitersdk/samples/ProjectApollo/src_saturn/sat5mesh.cpp

- Disable Rolling, landing, speedbrake, crash sound which causes issues in Orbiter 2016.
- Removed crash sound that is played at interstage separation from SII flight
- FOV is set according to users resolution in the LM LPD view, up to a max FOV of 60
- Removed FOV 40 being set in LM dock view (fwd COAS) Like the CSM forward COAS, the user can adjust FOV at their discretion
- Rotated the LM upper hatch view 180 degrees so to correspond with reality
- Adjusted various camera offset positions in the LM
- Initialize LM batteries 2 & 3 to low voltage as per documenation (LM-8 and prior)
- Resetting CSM power to LM will now set LM batteries 1 to 4 to low voltage (LM-8 and prior)

Various Fixes:

---

Orbitersdk/samples/ProjectApollo/src_lm/LEM.cpp
Orbitersdk/samples/ProjectApollo/src_lm/LEM.h
Orbitersdk/samples/ProjectApollo/src_lm/lemmesh.cpp
Orbitersdk/samples/ProjectApollo/src_lm/lemsystems.cpp
Orbitersdk/samples/ProjectApollo/src_lm/lemvc.cpp

- Add flag to indicate when camera is internal/external to update meshes/views accordingly (fixes wrong view when in upper hatch view and going to external and back to internal view)
- FOV handling now reads the new flag for proper restoration of previous FOV when going to external view from LPD or AOT windows.
- LM mesh loading has been moved to clbkSetClassCaps. This fixes an issue where when the LM is initially created (SIVB separation), the DEVMESHHANDLE's (crew, drogue, probes) are not properly initialized.

A few updates/fixes to the LM:

---

Orbitersdk/samples/ProjectApollo/src_csm/CSMcomputer.cpp
Orbitersdk/samples/ProjectApollo/src_lm/LEMcomputer.cpp
Orbitersdk/samples/ProjectApollo/src_sys/dsky.h

On restart the AGC does a GOJAM and a TC to 04000, these both take 1 MCT to complete,
Up until now we didn't simulate this delay.
I also removed an unused function and fixed some of the indentation (as I always do :p)

Delay AGC on restart and misc.

---

Orbitersdk/samples/ProjectApollo/src_csm/csm_telecom.cpp
Orbitersdk/samples/ProjectApollo/src_lm/lm_rr.cpp

fix bug where transponder would not recognize when LM RR was switched off. also re-added skin-tracking with a much lower gain, because its probable that this would work to some degree, and also catches some loss-of-signal conditions where the XPNDR is off.

minor bug-fix for LOS/AOS behavoir of LEM RR by CSM RRT

---

Orbitersdk/samples/ProjectApollo/src_csm/CSMcomputer.cpp
Orbitersdk/samples/ProjectApollo/src_csm/satsystems.cpp
Orbitersdk/samples/ProjectApollo/src_lm/LEMcomputer.cpp
Orbitersdk/samples/ProjectApollo/src_sys/apolloguidance.cpp
Orbitersdk/samples/ProjectApollo/src_sys/apolloguidance.h
Orbitersdk/samples/ProjectApollo/src_sys/dsky.cpp
Orbitersdk/samples/ProjectApollo/src_sys/yaAGC/agc_engine.h
Orbitersdk/samples/ProjectApollo/src_sys/yaAGC/agc_engine_init.c

VoltageAlarm was only present on our version and is no longer needed as RestartLight does the same.
PGNS also gets triggered by the TRACKER light.
#551

Remove VoltageAlarm, Correct PGNS light

---

Orbitersdk/samples/ProjectApollo/src_csm/satsystems.cpp
Orbitersdk/samples/ProjectApollo/src_sys/PanelSDK/Internals/Esystems.cpp
Orbitersdk/samples/ProjectApollo/src_sys/PanelSDK/Internals/Esystems.h

Internal resistance is taken as 0.0346667ohms which gives approximately predicted results(27 volts at 1420 watts), and you can get bus under-volt alarms by drawing more than the max on a single cell, as long as you don't draw enough to trip the FC disconnect. Any systems that are expecting a min voltage of exactly 28.8 V may be effected, but if they are set to the specs from the systems handbook they should behave as expected.

Make fuel cells' output voltage drop with increasing load.

---

Orbitersdk/samples/ProjectApollo/src_sys/PanelSDK/Internals/Esystems.cpp

Inserting the values resulted in the fuel cell temperature in existing scenarios to be loaded as clogging value, this results in the fuel cells failing. This patch ignores the old value and appends them instead.

Make new fuel cell clogging backwards compatible

---

Orbitersdk/samples/ProjectApollo/src_csm/saturn.cpp
Orbitersdk/samples/ProjectApollo/src_csm/saturn.h
Orbitersdk/samples/ProjectApollo/src_csm/saturnvc.cpp
Orbitersdk/samples/ProjectApollo/src_saturn/s1c.cpp

Improvement of the originally G-load driven shaking of the virtual cockpit. Now the visualized vibration is a superposition of three factors:
- G-load based offset of the viewpoint (practically head movement due to the G-load caused by thrust and aerodynamic forces)
- Noise-like viewpoint jostling of viewpoint depending on  altitude (reflected shockwaves); on dynamic pressure (aerodynamic vibration) and on thruster activity (engine vibration carried to the cockpit by the structure)
- longitudinal oscillation (POGO effect) depending on the phase of the launch.
The simulation of noise and longitudinal oscillation is based on Mission Reports, Launch Vehicle Flight Evaluation Reports and other sources (the most useful ones were Saturn V Launch Vehicle Flight Evaluation Report - AS-506, Apollo …

Visualization of vibration and POGO effects for CSM virtual cockpit

---

Orbitersdk/samples/ProjectApollo/src_launch/rtcc.cpp

Note: This is a PR for NASSP 7, not NASSP 8.
This little fix prevents issues with the Apollo 8 MCC-1 calculation. The uninitialized variable calcParams.LOI is used as the target time  for LOI. In rare case, like Orbiter Forum user STS experienced on his attempt to fly the mission in real-time, the correct time isn't assigned to the LOI variable and a random time is used as the target. In the case STS experience this was still close, but not equal to 0. The variable got saved as 0 in the scenario though, which made the bug fix itself after reloading the scenario. When you try to fly the mission in one go that is of course undesirable. The bug got fixed for NASSP 8 a long time ago, see: https://github.com/orbiternassp/NASSP/commit/c3f1fa0f685f740d2d65199dfa6ae193a4e12f2f#diff-8d69a445065b349 …

RTCC: Add initialization for LOI time
